### PR TITLE
Update EB roles to work with 5.7 ini settings

### PR DESCRIPTION
**Pull request by jorissteyn**
EngineBlock 5.7 does not work without an explicitly configured hostname, see:

 - https://www.pivotaltracker.com/story/show/155617973
 - https://github.com/OpenConext/OpenConext-engineblock/pull/515

@quartje lots of options are obsolete in 5.7 and can be removed, they are listed under the headings "Removed metadata backends" and "Removal of legacy INI settings" in https://github.com/OpenConext/OpenConext-engineblock/blob/master/UPGRADING.md.

### CODE REVIEW

**Comment by jorissteyn** [comment]
Bart, the following defaults have been removed from EB (in favour of example.org). This means we need to add them to the application.ini.j2 here in order to keep the same configuration:

```
pdp.baseUrl = "https://pdp.surfconext.nl/decide/policy"

attributeAggregation.baseUrl = "https://aa.surfconext.nl/aa/api/attribute/aggregate"

addgueststatus.guestqualifier = "urn:collab:org:surf.nl"

cookie.lang.domain = ".surfconext.nl"

defaults.title      = "SURFconext"
defaults.header     = "SURFconext"

edugain.publication.publisher = "https://engine.surfconext.nl/authentication/proxy/edugain-metadata"
edugain.registration.authority = "http://www.surfconext.nl/"
edugain.registration.policy = "https://wiki.surfnet.nl/display/eduGAIN/EduGAIN"

email.help = "help@example.org"

email.idpDebugging.from.name  = "SURFconext EngineBlock"
email.idpDebugging.from.address = "noreply@surfnet.nl"
email.idpDebugging.to.address = "surfconext-beheer@surfnet.nl"
email.idpDebugging.to.name    = "SURFconext Beheer"

openconext.termsOfUse = "https://wiki.surfnet.nl/display/conextsupport/Terms+of+Service+%28EN%29"
```

**Comment by jorissteyn** [comment]
I've added the "translation overrides" for SURFconext (no longer part of EB since 5.7) in a temporary branch. These two files need to be placed in languages/ for SURFconext:

 - [overrides.en.php](https://github.com/OpenConext/OpenConext-engineblock/blob/translation-surfconext-overrides/languages/overrides.en.php)
 - [overrides.nl.php](https://github.com/OpenConext/OpenConext-engineblock/blob/translation-surfconext-overrides/languages/overrides.nl.php)

**Comment by quartje** [comment]
I've added and removed the relevant configuration settings. This should be safe to merge, all settings that are removed from EB > 5.7 are made conditional based on {{ engine_version }}

**Comment by thijskh** [comment]
installation of environment specific overrides needs to be made optional. merged to master with that change

**Pull request closed without merging**
