### PR TITLE
Add statefile to /tmp

### PR DESCRIPTION
**Pull request by mvdheenux**
useful for rolling updates

### CODE REVIEW

**Comment by quartje** [comment]
Thanks for the PR!  Since there are two different VRRP instances, wouldn't it make more sense to have different statefiles for each instance? 
And out of curiosity: In what way is this statefile used during rolling updates?

**Comment by mvdheenux** [comment]
Quick response ;). 
Regarding your first question: In most cases, yes. But for this specific use-case I think this isn't adding much functionality. I'll share this playbook with you for reference. 
These statefiles are being used by another Ansible playbook that provides rolling updates by altering Keepalived config. It checks for both statefiles (per host) to contain "backup" before proceeding with installing patches & rebooting. It does this for one host at a time, because time isn't a big concern when patching during the day.

**Comment by quartje** [comment]
I think that you don't get reliable results using the same state file for both instances, since one is always backup and the other always master. Whatever instance writes as last its state to this file decides the state of both. Suppose that the backup instance has written its state, and you want to perform a failover of the master instance  on that host, you wait for the state to be `backup`. But since the statefile already contains `backup` it will not wait.

**Comment by mvdheenux** [comment]
The statefile is located on the host I want to patch, and within that host it's separated between IPV4 and IPV6. So since the statefiles are unique with each host, there should be reliable results. That's what I got back from my own testing at least ;).

**Review by quartje — APPROVED** [review]
Seems good to go!

**Pull request merged**
